name: Tests

on: [push, pull_request]

jobs:
  unit-benchmark-test:
    strategy:
      matrix:
        go: ["1.20"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

        # block scenario, comment temporarily
      #      - uses: actions/cache@v3
      #        with:
      #          path: ~/go/pkg/mod
      #          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #          restore-keys: |
      #            ${{ runner.os }}-go-

      - name: Unit Test
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./...
